#!/bin/sh                                                                                                                                                                                                                                                 
/var/lib/rrd/rrdtool.sh $1  > /dev/null 2>&1
